(defun gps-line ()
  (interactive)
  (let ((start (point-min))
	(n (line-number-at-pos))
	(total 0))
    (save-excursion
      (goto-char (point-min))
      (while (not (eobp))
		(if (char-equal (char-after) ?\n)
	    	(setq total (+ total 1))
	  	  )
		(forward-char 1)
		)
      (if (= start 1)
	  	  (message "Line %d/%d" n total)
		(save-restriction
	  	  (widen)
	  	  (message "line %d/%d (narrowed line %d/%d)"
		  		(+ n (line-number-at-pos start) -1) n)
	  	  )
		)
      )
    )
  )
